In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [3]:
type(my_list)

list

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# linspace

In [8]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
# Below Creates random numbers 0 to 5 twenty times

In [9]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [10]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

# Arrange

In [11]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# Zeros and Ones

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

# Eye

In [ ]:
np.eye(4) # makes a diagnal line in the array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

## rand

## Creates an array of the given shape and populates it with random samples froma. uniform distribution over [0,1)

In [ ]:
np.random.rand(2) # Rand generates only a number between[0,1]

array([0.21702844, 0.58813572])

In [21]:
np.random.rand(4)

array([0.32639291, 0.15260437, 0.83149813, 0.9234383 ])

In [ ]:
np.random.rand(5,5) # works with arrays

array([[0.47226879, 0.44182616, 0.71743662, 0.08052749, 0.28588518],
       [0.28892304, 0.63505663, 0.31152165, 0.18824501, 0.94432571],
       [0.99505798, 0.01457069, 0.32403739, 0.51118771, 0.53253928],
       [0.67211868, 0.00883977, 0.11811874, 0.85466758, 0.11095054],
       [0.10702063, 0.68144693, 0.84638083, 0.42777884, 0.0887418 ]])

## Randint

### Returns random integers where the lowest number is inclusive but the highest exclusive

### Return random integers from low (inclusive) to high (exclusive)

In [75]:
np.random.randint(1,100) # generate a random number from lower bound to upper bound
                         # lower bound number is included while upper number is excluded

81

In [26]:
np.random.randint(1,100,10) # third number is for how many numbers in the array print 

array([17, 21, 64, 56, 27, 90, 61, 91, 56, 29])

## seed

### Can be used to set the random state, so that the same "random" resultes can be reproduced

In [84]:
np.random.seed(67)
np.random.rand(4)

array([0.54585143, 0.85885661, 0.68589259, 0.33159182])

In [86]:
np.random.seed(67)
np.random.randint(1,100,4)

array([68, 54, 75, 70])

# Array Attributes and Methods

In [89]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [91]:
ranarr

array([40, 35, 30, 36, 31, 46, 45, 33, 42, 26])

# Reshape

In [ ]:
arr.reshape(5,5) # Reshaping just turns a regular array into 2D dimensions you provide for it in this case 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### These examples below show that you need perfect numbers to get an equal array so a prime number would not work

In [95]:
arr.reshape(3,8)

ValueError: cannot reshape array of size 25 into shape (3,8)

In [96]:
arr.reshape(3,10)

ValueError: cannot reshape array of size 25 into shape (3,10)

# Max, Min, Argmax, Argmin

In [97]:
ranarr

array([40, 35, 30, 36, 31, 46, 45, 33, 42, 26])

In [98]:
ranarr.max()

np.int64(46)

In [ ]:
ranarr.argmax() # returning the position of the list
                # list starting w/ 0 

np.int64(5)

In [100]:
ranarr.min()

np.int64(26)

In [101]:
ranarr.argmin()

np.int64(9)

# Shape

In [ ]:
arr # from rand generated

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [107]:
# Vector
arr.shape

(25,)

In [ ]:
#Notice the two sets of brackets
arr.reshape(1,25) # 1 row 25 colums

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape 

(1, 25)

In [ ]:
arr.reshape(25,1) # 25 rows 1 columns
# like an index and reshape to rows and colums (x,y)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])